ARG GO_DOCKER_VERSION=1.24

FROM golang:${GO_DOCKER_VERSION}-alpine AS builder

ENV APP_DIR=/app

WORKDIR $APP_DIR

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -trimpath -ldflags="-s -w" -o /app/app ./cmd/app/main.go

FROM alpine:latest

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

WORKDIR /app

COPY --chown=appuser:appgroup --from=builder /app/app .

USER appuser

EXPOSE 8080

CMD ["./app"]
