
name: template

services:
  go:
    build:
      context: ../app
      dockerfile: ../docker/images/alpine/Dockerfile.development
    container_name: template-go-development
    restart: unless-stopped
    working_dir: /app
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internal
      - public
    ports:
      - "8080:${APP_LISTEN_PORT:-8080}"   # HTTP
      - "2345:2345"   # Debug delve
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      - ../app:/app:cached

  postgres:
    image: postgres:17-alpine
    container_name: template-postgres-development
    restart: always
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: db_database
    ports:
      - "5432:5432"
    networks:
      - internal
    volumes:
      - ./volumes/development/postgres_data:/var/lib/postgresql/data:cached
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_user -d db_database"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  internal:
    driver: bridge
    internal: true
  public:
    driver: bridge
    internal: false
